export const MEDICAL_SPECIALIZATIONS = [
  'Allergy and Immunology',
  'Anesthesiology',
  'Bariatric Surgery',
  'Cardiac Electrophysiology',
  'Cardiothoracic Surgery',
  'Cardiology',
  'Child and Adolescent Psychiatry',
  'Clinical Genetics',
  'Clinical Hematology',
  'Clinical Immunology',
  'Clinical Pharmacology',
  'Colorectal Surgery',
  'Critical Care Medicine',
  'Dentistry',
  'Dermatology',
  'Developmental Pediatrics',
  'Diabetology',
  'Emergency Medicine',
  'Endocrine Surgery',
  'Endocrinology',
  'Epileptology',
  'Family Medicine',
  'Female Pelvic Medicine',
  'Fetal Medicine',
  'Forensic Medicine',
  'Gastroenterology',
  'General Medicine',
  'General Surgery',
  'Geriatric Medicine',
  'Geriatric Psychiatry',
  'Gynecologic Oncology',
  'Gynecology',
  'Hand Surgery',
  'Head and Neck Surgery',
  'Hematology',
  'Hepatobiliary Surgery',
  'Hepatology',
  'Hospital Medicine',
  'Infectious Disease',
  'Internal Medicine',
  'Interventional Cardiology',
  'Interventional Radiology',
  'IVF and Reproductive Medicine',
  'Laparoscopic Surgery',
  'Medical Oncology',
  'Microbiology',
  'Neonatology',
  'Nephrology',
  'Neuro Critical Care',
  'Neuro Oncology',
  'Neurology',
  'Neurophysiology',
  'Neurosurgery',
  'Nuclear Medicine',
  'Obstetrics',
  'Obstetrics and Gynecology',
  'Occupational Medicine',
  'Oncology',
  'Ophthalmology',
  'Optometry',
  'Oral and Maxillofacial Surgery',
  'Orthodontics',
  'Orthopedic Oncology',
  'Orthopedic Surgery',
  'Otolaryngology',
  'Pain Medicine',
  'Palliative Care',
  'Pathology',
  'Pediatric Cardiology',
  'Pediatric Critical Care',
  'Pediatric Dentistry',
  'Pediatric Endocrinology',
  'Pediatric Gastroenterology',
  'Pediatric Hematology and Oncology',
  'Pediatric Infectious Disease',
  'Pediatric Nephrology',
  'Pediatric Neurology',
  'Pediatric Orthopedics',
  'Pediatric Pulmonology',
  'Pediatric Rheumatology',
  'Pediatric Surgery',
  'Pediatrics',
  'Periodontics',
  'Physical Medicine and Rehabilitation',
  'Physiotherapy',
  'Plastic and Reconstructive Surgery',
  'Podiatry',
  'Preventive Medicine',
  'Prosthodontics',
  'Psychiatry',
  'Psychology',
  'Pulmonary Medicine',
  'Radiation Oncology',
  'Radiology',
  'Reproductive Endocrinology',
  'Respiratory Medicine',
  'Rheumatology',
  'Sleep Medicine',
  'Spine Surgery',
  'Sports Medicine',
  'Surgical Gastroenterology',
  'Surgical Oncology',
  'Thoracic Surgery',
  'Transfusion Medicine',
  'Trauma Surgery',
  'Urogynecology',
  'Urology',
  'Vascular Medicine',
  'Vascular Surgery'
];

export const SPECIALIZATION_OPTIONS = Object.freeze(
  [...new Set(MEDICAL_SPECIALIZATIONS)].sort((a, b) => a.localeCompare(b))
);
